### ISSUE TITLE
HtmlRuleSanitizer expects HtmlAgilityPack to be exact 1.4.9

### ISSUE THREAD

**Issue by leotsarev** [Vereyon/HtmlRuleSanitizer#10]
Hi, when I trying to update NuGet reference to HtmlAgilityPack to latest stable version, this causing unexpected breakage when I try to run;

    System.IO.FileLoadException: Could not load file or assembly 'HtmlAgilityPack, Version=1.4.9.5, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)**

Stacktrace 
Vereyon.Web.HtmlSanitizer.Sanitize(String html)

M.b. I'm doing something wrong, however...

**Comment by cakkermans** [comment]
According to https://www.nuget.org/packages/Vereyon.Web.HtmlSanitizer/ you only need HtmlAgilityPack 1.4.9 or higher. All other versions are pretty old. What version of HtmlAgilityPack are you using?

I however see that your code is trying to locate 1.4.9.5, which is weird. I'm looking into it.

**Comment by leotsarev** [comment]
I still fighting with it without any success.
However, I can't reproduce it on empty project
