### ISSUE TITLE
em tag gets deleted completely

### ISSUE THREAD

**Issue by lbmankala** [Vereyon/HtmlRuleSanitizer#12]
em tag gets deleted completely as shown in below:

![em_replacement](https://cloud.githubusercontent.com/assets/16317385/23705441/d8cedf8e-042f-11e7-8861-e3d1dfb725ec.png)

Its supposed to be, but after sanitization whole text gets deleted.
<p style="text-align: right;"><em><strong>Bold text</strong></em></p>

I have included p, em, strong,  along with other html tags in whitelist . Still its getting deleted.

**Comment by cakkermans** [comment]
For me, this simply works as supposed:

```
var sanitizer = new HtmlSanitizer();
sanitizer.Tag("p");
sanitizer.Tag("em");
sanitizer.Tag("strong");

var input = @"<p style=""text-align: right;""><em><strong>Bold test</strong></em></p>";
var expected = @"<p><em><strong>Bold test</strong></em></p>";
var output = sanitizer.Sanitize(input);
Assert.Equal(expected, output);
```

Please post your full configuration if you are still having problems.
