### ISSUE TITLE
Enforce single quotes instead of double quotes for attributes

### ISSUE THREAD

**Issue by lavkumarv** [Vereyon/HtmlRuleSanitizer#15]
Hi,
This library works fine for all my use cases. But for some cases, I need to add the HTML attribute in single quotes instead of double.

Like
original string  `<a href='www.example.com'>`
after setting target attribute it becomes  `<a href='www.example.com' target="_blank">`
but need  `<a href='www.example.com' target='_blank'>`

Do you have any option to do it?

**Comment by cakkermans** [comment]
Unfortunately there is no feature to do this. The [HTML5 standard](https://html.spec.whatwg.org/#attributes-2) allows single, double and no quotes on attributes, so there is nothing wrong with them.

The HtmlAgilityPack does seem to be able to read and control the quote type on attributes using `HtmlAttribute.QuoteType`, so I think this feature could be developed.

**Comment by cakkermans** [comment]
This feature was implemented in version 1.8 and is now available
