### ISSUE TITLE
Multi-targeted assemblies and NuGet package

### ISSUE THREAD

**Issue by dahall** [Vereyon/HtmlRuleSanitizer#18]
If you are using VS2017 as your IDE, you can convert the project so that it will build against multiple target framework versions (e.g. 3.5, 4.0, 4.5 and .NET Standard 2.0) and automatically package them into a NuGet package. If this is something you'd consider doing, let me know and I'll do the work and submit a Pull Request. This would help on a project I'm doing.

**Comment by cakkermans** [comment]
I saw you enabled multi targeting in the project, thanks.

Is there any reason to target both .NET 4 and 4.5, and .NET Standard 1.3 and 2.0? To my knowledge the sole difference between .NET 4 and .NET 4.5 is a larger API surface of 4.5. Any assembly targeting .NET 4 will also work on 4.5. The same applies to .NET Standard 1.3 and 2.0.

**Comment by dahall** [comment]
Yes. There were a number of features introduced in 4.5 and Std 2.0 that I have used conditional compilations to provide backwards compatibility. For 4/4.5, you are correct in that it loads the same assemblies, so technically you could, for this project with no compatibility issues, just delivery 4.0. Different though for .NET Standard. The separate builds prevent side-loading multiple assemblies, especially when using 2.0. To your point, I would just eliminate the 4.5 build from the list if it were me.

**Comment by cakkermans** [comment]
This suggestion has been implemented. All projects now multi-target. Thanks!
