### ISSUE TITLE
Question: allow iframe with specific domain?

### ISSUE THREAD

**Issue by leotsarev** [Vereyon/HtmlRuleSanitizer#19]
How could I allow adding iframes only to whitelisted domains? I like to allow youtube.com, but not evilsiteexample.com

**Comment by leotsarev** [comment]
@cakkermans It this possible with HtmlRuleSanitizer? If not, will you accept PR for that?

**Comment by leotsarev** [comment]
That's problem I'm trying to solve https://stackoverflow.com/questions/50541435/markdown-in-user-comments-with-proper-sanitize-and-youtube-videos

**Comment by leotsarev** [comment]
@cakkermans ? I just need "yes, I'll accept PR for that" from you.

**Comment by leotsarev** [comment]
@cakkermans ? polite ping ?

**Comment by cakkermans** [comment]
@leotsarev, in the current design this would be possible by implementing an extra attribute check. Unfortunately I think this not really extendable in the current design: the number of different types of supported checks is locked by the `HtmlSanitizerCheckType` enum.

I would suggest opening up that registry, and perhaps make the `AttributeCheckRegistry` dictionary string based. Or perhaps do away with it completely and directly store the delegates in `HtmlSanitizerTagRule.CheckAttributes`. The delegates should not be much more than a dozen bytes each anyway, which would be comparable to typical name string.

I would gladly accept a pull request, but do note that this change will probably be breaking, so we'll need to up the version.

**Comment by leotsarev** [comment]
I think it solved by `IHtmlAttributeSanitizer` and could be closed
