### ISSUE TITLE
Error when parsing mailto href attributes

### ISSUE THREAD

**Issue by jbray1982** [Vereyon/HtmlRuleSanitizer#23]
The following unit test runs correctly:
```
        [Fact]
        public void AHrefUrlCheckMailToTest()
        {

	        string result;
	        var sanitizer = new HtmlSanitizer();
	        sanitizer.Tag("a").CheckAttribute("href", HtmlSanitizerCheckType.Url);

	        // Test a relative url, which should pass.
	        var input = @"<a href=""mailto:test@example.com?subject=test"">MailTo</a>";
	        var expected = @"<a href=""mailto:test@example.com?subject=test"">MailTo</a>";
	        result = sanitizer.Sanitize(input);
	        Assert.Equal(expected, result);
        }
```

Howver, if you have a space in the subject argument:
```
        [Fact]
        public void AHrefUrlCheckMailToTest()
        {

	        string result;
	        var sanitizer = new HtmlSanitizer();
	        sanitizer.Tag("a").CheckAttribute("href", HtmlSanitizerCheckType.Url);

	        // Test a relative url, which should pass.
	        var input = @"<a href=""mailto:test@example.com?subject=test this"">MailTo</a>";
	        var expected = @"<a href=""mailto:test@example.com?subject=test this"">MailTo</a>";
	        result = sanitizer.Sanitize(input);
	        Assert.Equal(expected, result);
        }
```

The test fails. You can work around this by using %20 instead of space in the input string.

**Comment by cakkermans** [comment]
Hi @jbray1982, thanks for reporting this. Any chance you can add the (incorrect) output to this issue? I suspect some HTML encoding may be happening.

In addition, it this preventing the resulting href attribute from being valid? In other words, does the link work as it should, or is it broken after sanitation?

**Comment by jbray1982** [comment]
Hello, sorry for the late response. The output when you have spaces in your mailto link is that the whole thing is stripped and rendered as plain text. I am attaching the output below. Since the link is not rendered, it does not work. 

``Xunit.Sdk.EqualException
Assert.Equal() Failure
          ↓ (pos 0)
Expected: <a href="mailto:test@example.com?subject=···
Actual:   Relative link
          ↑ (pos 0)
   at Vereyon.Web.AttributeCheckTests.AHrefUrlCheckMailToTest() in C:\Work\HtmlRuleSanitizer-master\Web.HtmlSanitizer.Tests\AttributeCheckTests.cs:line 68``

**Comment by cakkermans** [comment]
Hi @jbray1982, I traced your issue to the usage of [Uri.IsWellFormedOriginalString()](https://docs.microsoft.com/en-us/dotnet/api/system.uri.iswellformeduristring?view=netframework-4.8). Essentially this means that the url you are passing `mailto:test@example.com?subject=test` is not a well formed url according to RFC 2396 or RFC 2732.

So there is little I can do about this except suggesting to ensure the url's are correctly formatted, or turning off the attribute check. Unfortunately the attribute check itself is not readily extensible right now.

**Comment by jbray1982** [comment]
Okay thanks for looking into it. For now I have a line of code that parses out the href attributes and replaces any spaces with %20. If anyone else finds this issue that is a workaround.

**Comment by cakkermans** [comment]
Hi @jbray1982, to further help out your case I implemented customizable attribute sanitation. This is now available as a [prerelease package](https://www.nuget.org/packages/Vereyon.Web.HtmlSanitizer/1.6.0-beta1).

Docs in the repo are already updated, but I'll probably have to tidy a few things up before I can release it for real. Good luck!

I am closing this issue as you mentioned you worked around it, and because the URL you are having trouble itself does not comply to the RFC.
