### ISSUE TITLE
Multithreaded use of .Sanitize ?

### ISSUE THREAD

**Issue by JiriZidek** [Vereyon/HtmlRuleSanitizer#24]
Is it safe to craft an instance of HtmlSanitizer either by lazy singleton or as a static memeber field, and then use it from various threads (i.e. from multiple parallel http requests processing) ?
Or the only way is to create a new instance for each thread - in my case for each http request ?

**Comment by cakkermans** [comment]
I did not take special care making the sanitizer thread safe.

I recommend creating a new instance of HtmlSanitizer for every thread. Creating the instance is a cheap operation, so there won't be a lot of overhead from doing so.
