### ISSUE TITLE
Missing documentation in NuGet packages

### ISSUE THREAD

**Issue by jeldert** [Vereyon/HtmlRuleSanitizer#25]
When I build the project on my local machine in release mode, the generated NuGet package contains the `Vereyon.Web.HtmlSanitizer.xml` file inside the NuGet package.

However, the file hosted on NuGet.org (https://www.nuget.org/packages/Vereyon.Web.HtmlSanitizer/1.6.0) does not contain this file.

When using HtmlSanitizer in a project, IntelliSense does not show the documentation:
![image](https://user-images.githubusercontent.com/12424446/105205349-76447100-5b45-11eb-854c-816ba26d3b16.png)

Local generated NuGet package (release mode):
![image](https://user-images.githubusercontent.com/12424446/105205082-22d22300-5b45-11eb-9680-b04546d03365.png)

Online hosted NuGet package:
![image](https://user-images.githubusercontent.com/12424446/105205165-3b423d80-5b45-11eb-94cc-a9b521405244.png)

**Comment by cakkermans** [comment]
Oh, that's not so neat. Thanks for informing me @jeldert. I pushed a new release 1.6.0.1, which does include documentation.
