### ISSUE TITLE
How to report security issues

### ISSUE THREAD

**Issue by leeN** [Vereyon/HtmlRuleSanitizer#29]
Hello there,

I found that is it possible to craft inputs to bypass the HtmlRule sanitizer and achieve XSS. It is not quite clear how to report them without dumping them in a public Github issue, which I'd rather avoid for obvious reasons.
I tried messaging contact@vereyon.nl but got no response - so is there a better way to get in touch?

Cheers,
leeN

**Comment by cakkermans** [comment]
Hi @leeN, sorry for missing this. I didn't check in for some time. Reach me at christ_akkermans@hotmail.com .
