### ISSUE TITLE
[BREAKING] No longer possible to override UrlCheckerAttributeSanitizer or construct it instance

### ISSUE THREAD

**Issue by leotsarev** [Vereyon/HtmlRuleSanitizer#31]
Previously  I was able to create my own sanitizer AllowWhiteListedIframeDomains based on UrlCheckerAttributeSanitizer

It was like:
```
internal class AllowWhiteListedIframeDomains : UrlCheckerAttributeSanitizer
{
    private AllowWhiteListedIframeDomains() { }
    public static AllowWhiteListedIframeDomains Default { get; private set; } = new AllowWhiteListedIframeDomains();

    protected override bool AttributeUrlCheck(HtmlAttribute attribute)
    {
        var baseResult = base.AttributeUrlCheck(attribute);
        if (!baseResult)
        {
            return false;
        }

        if (attribute.Value.StartsWith("https://music.yandex.ru/iframe/")
            || attribute.Value.StartsWith("https://www.youtube.com/embed/")
            || attribute.Value.StartsWith("https://ok.ru/videoembed/")
            )
        {
            return true;
        }

        return false;
    }
}
```

Now its no longer possible, because UrlCheckerAttributeSanitizer defaults to empty list of allowed schemes and only code internal to `HtmlRuleSanitizer` assembly can set schemes. 

Solutions:

1. If UrlCheckerAttributeSanitizer doesn't mean to use outside of assembly, let's make it internal (and remove virtual from AttributeUrlCheck)
2a. Make setter for AllowedUriSchemes publicly accessible (or at least protected internal). 
2b. Or even make it constructor argument.

**Comment by leotsarev** [comment]
made PR for 2b for demonstration

**Comment by leotsarev** [comment]
@cakkermans  ?

**Comment by leotsarev** [comment]
@cakkermans  ??

**Comment by cakkermans** [comment]
Hi @leotsarev, sorry for not getting back to this earlier.

Looking at the code I have to admit I agree that it is 'odd' that the `AllowedUriSchemes` property has an `internal` setter. This indeed complicates subclassing / deriving from `UrlCheckerAttributeSanitizer`. So my proposal would be to implement that change. Can you confirm that this sufficiently helps you?

**Comment by leotsarev** [comment]
2a and 2b is sufficiently for me

**Comment by leotsarev** [comment]
Thanks

**Comment by cakkermans** [comment]
Please get package version 1.7.1, which should now be available on NuGet.
