### ISSUE TITLE
Relative urls in anchor tag throw an exception

### ISSUE THREAD

**Issue by ideaMarcos** [Vereyon/HtmlRuleSanitizer#4]
Changing your UrlCheckTest() to 
`var inputIllegal = @"<a href=""../relative.htm"">Relative link</a>";`

causes AttributeUrlCheck() to throw an InvalidOperationException by the uri.Scheme property. You need to add an absolute uri check
`if (!uri.IsWellFormedOriginalString() || !uri.IsAbsoluteUri)`

**Comment by cakkermans** [comment]
Thanks for reporting this. I checked it and you are correct.

The URL check now only checks the scheme when dealing with an absolute URL. I pushed a new version to NuGet as well.
