### ISSUE TITLE
Remove dangerous characters like closing tag or opening tag

### ISSUE THREAD

**Issue by pawepaw** [Vereyon/HtmlRuleSanitizer#6]
Hello,

I've spotted that you do not remove empty closing tags which is very dangerous i.e:
`\"><style>html {background:pink;} body{ display:none; }</style>`

Is there any plan to implement it or should i contrib with it?

**Comment by cakkermans** [comment]
Could you give a more elaborate sample of a HTML fragment which is not parsed correctly and also what the desired output would be?

Prior to sanitizing the HTML the HTML is processed into a DOM, on which sanitation is performed and the resulting DOM is serialized to HMTL again. So any empty closing tags should not even make it into the DOM representation. But hey, I might be wrong. I would be nice to have a test case.

**Comment by pawepaw** [comment]
Test case is what I wrote above: `\"><style>html {background:pink;} body{ display:none; }</style>`

desired output would be empty string (img is not allowed)  but i get`\">` 

if you want I can upload test on some branch to give you example.

**Comment by cakkermans** [comment]
Okay I tested it and see the problem. The parser correctly recognizes that the `\">` is not part of any proper HTML element and treats it as a text elements. For some reason I am surprised to see that the `"` and `>` characters are not HTML escaped after sanitation.

I'll try to look for a solution the coming days. But I am getting a hunch that this may require swapping out the HTML parser...

**Comment by cakkermans** [comment]
@pawepaw Could you check out commit 9241f74c060f0fb4af3a26ce7b0b95ad3d009204? I think this commit solves your problem. I ensured that absolutely all HMTL syntax characters are entity encoded.

I am not completely happy with the solution yet as also any code point above 127 are also encoded and this is simply not required when using Unicode.

**Comment by pawepaw** [comment]
Not sure if encoding is a good idea. I'd rather rely on sanitization. After encoding all data will be saved on database. Sure it will be encoded but if there is another system reading from this database and it does not have same level of security (would encode it before save) it may open some xss attacks vectors. 

I.e
Imagine we have 2 systems (a and b) and one database. In system a user saves data 
"\"><style>html {background:pink;} body{ display:none; }</style>" and its properly sanitized and encoded using your mechanism. But when system b reads it, it's being decoded on view by browser and could save it again without encoding if there is no sanitization/encoding mechanism. 

So I think it's always safer to sanitize rather than encode. I'm not pretty sure how your mechanism (parser) works because i didn't analyze entire code but https://github.com/Vereyon/HtmlRuleSanitizer/commit/9241f74c060f0fb4af3a26ce7b0b95ad3d009204#diff-92ace0a9afea0bb9874aa0b04d923ea3R164 if i assume that all data needs to be inside html tag does it means that i can remove all data inside node.NodeType == HtmlNodeType.Text? 

i.e "\"><style>html {background:pink;} body{ display:none; }</style>"  it'll remove everything that it's not inside <style></style>. 

Or it'll also remove all text in nested html?
i.e "\"><style>html {background:pink;} body{ display:none; }<p>some text</p>Test123</style>"

**Comment by cakkermans** [comment]
Well, sanitization is still happening like it was. It's just that for all text nodes that it is ensured that for the content any HTML entities are correctly encoded. This prevents people from attempting to do funny business using HTML entities. The main concern tackled in this manner is that another HTML parser may trip over non encoded HTML entities, opening the door for attacks. Even if the tricks do not trip the parser of the sanitizer.

In you particular case you could opt to remove all text nodes which are directly in the document node, which is more or less what you propose. This will remove anything which is outside of any HTML tag.

In general this is however not a suitable solution because this prevents one from passing fragments of HTML to the sanitizer. A HTML fragment does not need to be wrapped in a tag to be valid. So I strongly recommend following the approach I took. I believe it adheres exactly to the W3C standard, except for that I would prefer Unicode characters not to get HTML encoded by default.

**Comment by pawepaw** [comment]
Sure I understand that sanitization is still happening but i wanted to point that encoding isn't as safe as sanitization and i think that we should sanitize all html dangerous content not encode it.

Yes i opt to remove all text nodes which are not nested in html tags. Maybe sanitizer should expose two methods? Sanitize document and sanitize html fragment? Where SanitizeDocument would asume that everything is nested inside html tag and sanitizehtmlfragment wouldn't assume so.

Anyway I didn't test it if closing tag is nested inside some html tag would it sanitize it? `<style> \">html {background:pink;} body{ display:none; }</style>` Will `\">` be sanitized if style is allowed?

**Comment by cakkermans** [comment]
HTML entity encoding is implemented in the latest release https://github.com/Vereyon/HtmlRuleSanitizer/releases/tag/v1.2.0

I checked the W3C HTML5 standard and I do not see any indication of HTML code being required to be wrapped in tags. Plain text surrounding the HTML code seems perfectly legal.

If you still feel the need for functionality like this I would suggest you perform these modifications on the dom in your own code, and call `HtmlSanitizer.SanitizeNode()` after having done these modifications.
